### ISSUE TITLE
网站建议

### ISSUE THREAD

**Issue by WilliamK7** [runningcheese/Awesome-AI#1]
https://chat.theb.ai
调用的是新的 chatgpt api 反应非常快，建议添加至列表中

**Comment by hoochanlon** [comment]
chatgpt，这儿有一条清单...慢慢筛选咯。
 
 * https://www.ooopn.com/tool/chatgpt/
 * https://chat.forchange.cn/
 * https://chat.bygpt.com
 * https://chatgpt.ddiu.io
 * https://github.com/varunshenoy/GraphGPT （自然语言生成流程图等知识图谱）
 * https://www.perplexity.ai （基于chatgpt的搜索引擎）
 * https://qigechatgpt.com
 * https://chatgpt.lcc8.com
 * https://ai.exacg.cc
 * https://askai.ws
 * http://www.gptjx.com
 * https://github.com/eon01/awesome-chatgpt
 * https://6om.net
 * https://inspo.vip
 * https://gpt.tool00.com
 * https://www.chatgoo.com
 * https://aigcfun.com
 * https://www.humata.ai （本地文件分析）
 * https://github.com/f/awesome-chatgpt-prompts
 * https://www.emergentmind.com
 * http://chat.h2ai.cn/home
 * https://ai.askai.top
 * https://askai.top/
 * https://merlin.foyer.work/
 * http://wenzhang.zhuluan.com/zh-cn/
 * https://aski.ai
 * https://learnprompting.org
 * https://poe.com/?ref=producthunt
 * https://huggingface.co/spaces/JavaFXpert/Chat-GPT-LangChain?continueFlag=479d7d9702f68b553f084eda4e2f97fb
 * https://cway.top/post/1054.html
 * https://sms-activate.org
 * https://www.cnblogs.com/csyh/p/chatgpt.html

**Comment by clayboby** [comment]
补一个我知道带GPT4的，https://www.vivi-chat.com/#/chat。挺快挺好用
