### ISSUE TITLE
go-proxy-bing停止维护，建议更换站点

### ISSUE THREAD

**Issue by laohutongzhi** [runningcheese/Awesome-AI#13]
演示站和项目早就停止维护了，新的 Fork 在这里：[https://github.com/Harry-zklcdc/go-proxy-bingai](https://github.com/Harry-zklcdc/go-proxy-bingai)，最新版 1.93
并且只能在没有被微软 ban 的 VPS 用 docker 部署
原issue：[issues #386](https://github.com/adams549659584/go-proxy-bingai/issues/386#issuecomment-1656995574)

**Comment by Harry-zklcdc** [comment]
> 演示站和项目早就停止维护了，新的 Fork 在这里：https://github.com/Harry-zklcdc/go-proxy-bingai，最新版 1.93 并且只能在没有被微软 ban 的 VPS 用 docker 部署 原issue：[issues #386](https://github.com/adams549659584/go-proxy-bingai/issues/386#issuecomment-1656995574)

并不是，目前我fork的演示站是用 vercel + cloudflare 实现的，不过就要求强制登录了，不能免登录使用
