### ISSUE TITLE
是否可以收录: WeChatAI

### ISSUE THREAD

**Issue by bingryan** [runningcheese/Awesome-AI#8]
刚刚开源: https://github.com/bingryan/WeChatAI

支持: Azure OpenAI/ OpenAI
各种个性化设置, 具体可以看readme

**Comment by GypsyGuy1996** [comment]
没太看懂这个是什么工具跟已有的集成盒子有什么区别？

**Comment by bingryan** [comment]
> 没太看懂这个是什么工具跟已有的集成盒子有什么区别？

聊微信一样，聊ai
